### ISSUE TITLE
ブログデザイン要件

### ISSUE THREAD

**Issue by tkengo** [tkengo/tkengo.github.com#1]
# ベース
- モダン
- 落ち着きのあるページ
- シンプル
- 派手じゃない
- 淡いパステル

※好きな色は青とか緑とか
# あったらいいなぁ
- ジブリっぽさ(トトロは特に好き)
- フッタでの遊び
# 好きなデザイン
- http://mark-story.com/ (CakePHP開発者。フッタ辺りとか好き)
- http://blog.instagram.com/ (Instagram。シンプルで好き)
- http://blog.alfredapp.com/ (Alfred。シンプルでいい)
- http://webdesignrecipes.com/ (かわいすぎだけどフッタの境目辺りとか好き)
- http://www.vagrantup.com/ (ブログじゃないけど...)

**Comment by tkengo** [comment]
今は顔写真が入ってるけど、必須ではない。

**Comment by keitakawamoto** [comment]
> 好きなデザイン

ナルホディウス

**Comment by keitakawamoto** [comment]
さあいい加減動かなければ

**Comment by tkengo** [comment]
む、そういえばこんなイシューがあったなｗ

**Comment by keitakawamoto** [comment]
忘却の彼方だったなw

**Comment by tkengo** [comment]
404ページもあったら欲しいなー

**Comment by keitakawamoto** [comment]
水面に浮かぶメ○の靴以外に考えられる？

**Comment by tkengo** [comment]
404生々しいなｗ

**Comment by keitakawamoto** [comment]
なんかアイデアあったらイメージ化するよー

**Comment by tkengo** [comment]
すこし考えてみる。

**Comment by keitakawamoto** [comment]
:eyes:

**Comment by keitakawamoto** [comment]
ちまちまと https://bitbucket.org/tkengo/octopress/branch/source-renewal でコーディング中。
ブログデザインということもあり、コーディングしながらデザインを考えるスタイルで進める。

**Comment by tkengo** [comment]
リニューアル完
